### ISSUE TITLE
Error running phpunit

### ISSUE THREAD

**Issue by mateo2181** [zaratedev/testing-laravel#1]
I have copied phpunit.xml from this project but when I run "./vendor/bin/phpunit" tests are executed  on Mysql instead sqlite and refresh my database (I am using use RefreshDatabase; in my tests).
I've tried a lot of configurations on my phpunit.xml but none works.

Do you know where can be the problem?

Thanks.

**Comment by zaratedev** [comment]
Hi @mateo2181 

For run your tests with phpunit

Use the command `/vendor/bin/phpunit`

Great

**Comment by mateo2181** [comment]
Yes, I did it. The problem is tests are running on my mysql database instead running in SQLite.

**Comment by zaratedev** [comment]
This should run test on sqlite
```xml
<env name="DB_CONNECTION" value="sqlite"/>
<env name="DB_DATABASE" value=":memory:"/>

```

**Comment by mateo2181** [comment]
Yes, I've tried that, but not works. 
I tried create file .env.testing too and set phpunit.xml with 
```
<env name="APP_ENV" value="testing"/>
``` 

but none works.

**Comment by zaratedev** [comment]
Attempt with another project.
